import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Send } from 'lucide-react'
import { Badge } from '../../components/ui/Badge'
import { PageHeader } from '../../components/ui/PageHeader'
import { adminKeys, getAdminSupport, type SupportStatus } from '../../api/admin'
import { Card, SectionHeader, dateShort } from './adminUtils'

export const AdminSupportPage = () => {
  const tickets = useQuery({ queryKey: adminKeys.support(), queryFn: getAdminSupport })
  const [selected, setSelected] = useState<any>(null)
  const [status, setStatus] = useState<SupportStatus>('Open')
  return <div className="space-y-6"><PageHeader title="Support Tickets" subtitle="Worker and client support queue." /><div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><Card><SectionHeader title="Ticket Queue" /><div className="grid gap-3 border-b border-border p-4 md:grid-cols-3"><select className="rounded-md border border-border px-3 py-2 text-sm"><option>Open</option><option>In Progress</option><option>Resolved</option></select><select className="rounded-md border border-border px-3 py-2 text-sm"><option>Worker</option><option>Client</option></select><select className="rounded-md border border-border px-3 py-2 text-sm"><option>High</option><option>Normal</option></select></div><div className="divide-y divide-border">{tickets.data?.map((ticket) => <button key={ticket.id} onClick={() => { setSelected(ticket); setStatus(ticket.status) }} className="w-full p-4 text-left hover:bg-surface"><div className="flex justify-between gap-2"><strong className="text-navy">{ticket.ticketNo}</strong><SupportBadge status={ticket.status} /></div><p className="mt-1 text-sm text-muted">{ticket.requester} · {ticket.type} · {ticket.priority}</p><p className="mt-1 font-semibold text-navy">{ticket.subject}</p><p className="text-xs text-muted">{ticket.category} · {dateShort(ticket.lastUpdated)}</p></button>)}</div></Card><Card><SectionHeader title="Ticket Detail" subtitle="Auto-closes in 3 days if no requester reply." />{selected ? <div className="flex min-h-[520px] flex-col"><div className="border-b border-border p-4"><h3 className="font-bold text-navy">{selected.subject}</h3><select value={status} onChange={(e) => setStatus(e.target.value as SupportStatus)} className="mt-3 rounded-md border border-border px-3 py-2 text-sm"><option>Open</option><option>In Progress</option><option>Resolved</option></select></div><div className="flex-1 space-y-3 p-4">{selected.messages.map((m: any, i: number) => <div key={i} className="rounded-lg bg-surface p-4"><p className="font-bold text-navy">{m.sender}</p><p className="mt-2 text-sm text-muted">{m.body}</p><p className="mt-2 text-xs text-muted">{dateShort(m.timestamp)}</p></div>)}</div><div className="border-t border-border p-4"><textarea placeholder="Admin reply..." className="min-h-24 w-full rounded-md border border-border px-3 py-2 text-sm" /><button className="mt-3 inline-flex items-center gap-2 rounded-md bg-blue px-4 py-2 text-sm font-bold text-white"><Send className="h-4 w-4" /> Send</button></div></div> : <p className="p-8 text-sm text-muted">Select a ticket.</p>}</Card></div></div>
}
const SupportBadge = ({ status }: { status: SupportStatus }) => status === 'Resolved' ? <Badge variant="approved">{status}</Badge> : status === 'In Progress' ? <Badge variant="pending">{status}</Badge> : <Badge variant="info">{status}</Badge>
